stages:
  nb-to-py:
    cmd: bash convert.sh
    deps:
      - get_state.ipynb
      - RLStock.ipynb
    outs:
      - get_state.py
      - RLStock.py
  get-state-pred:
    cmd: python get_state.py
    deps:
      - get_state.py
    outs:
      - metrics.txt
      - plot.png
      - pred.csv
    metrics:
      - metrics.json:
          cache: false
  #run-rl:
    #cmd: python CNN.py
    #deps:
      #- pred.csv
      #- CNN.py
    #outs:
      #- progress.png
      #- met.txt
