name: check_pipe
on:
  push:
    branches:
      - '*'
      - '!main'
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://iterativeai/cml:0-dvc2-base1-gpu
    steps:
      - uses: actions/checkout@v2
      - name: run pipe
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git config --global --add safe.directory /__w/RL-stocks/RL-stocks
            pip install -r require.txt
            dvc repro
            git fetch --prune
            
            dvc metrics diff --show-md main > report.md
            
            echo "## confusion matrix" >> report.md
            cml publish plot.png --md >> report.md
            
            cml send-comment report.md
